### ISSUE TITLE
external pointer not valid when sourcing file 

### ISSUE THREAD

**Issue by verajosemanuel** [r-dbi/RMariaDB#120]
I usually split R scripts by content, so first file is for data load and second for functions and such.
Everything worked ok if all is in just one file. When splitting if RMariaDB connections are in a separate file i get an error. All the rest worked ok.
```

 source("01-data-load.R")
Error in result_create(conn@ptr, statement, is_statement) : 
  external pointer is not valid
```

**Comment by krlmlr** [comment]
Thanks. This is by design: a connection object cannot be serialized to a file, it has to be reestablished in every new R session.

I suggest you extract a function that establishes the connection, and call that function at the beginning of your scripts. Take a look at the _pool_ package to avoid creating more connections than necessary.

**Comment by verajosemanuel** [comment]
thanks
