### ISSUE TITLE
Compilation on Windows latest + R3.6 seems to fail

### ISSUE THREAD

**Issue by mgirlich** [r-dbi/RMariaDB#317]
See the dbplyr run: https://github.com/tidyverse/dbplyr/actions/runs/6664449009/job/18112087560?pr=1374

**Comment by krlmlr** [comment]
@jeroen: any idea?

**Comment by jeroen** [comment]
I'd recommend to remove 3.6-windows from your testing matrix. I am no longer actively testing/building for R-3.6 on Win because it used a very old toolchain, and nobody really uses that anymore. We now need to support so many different toolchains on Windows for different versions of R, that this one fell off.

**Comment by mgirlich** [comment]
Which version of R would you recommend for Windows?

**Comment by jeroen** [comment]
> Which version of R would you recommend for Windows?

I'd recommend testing on Windows with at least R-4.1 and R-4.2 and R-release. That implicitly covers R-4.0 because it uses the same toolchain as R-4.1. 

Soon we may need to add clang toolchains but those are not yet ready.
